# Generated by Django 5.0 on 2023-12-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id_token', models.CharField(max_length=255)),
                ('client_secret_token', models.CharField(max_length=255)),
                ('chatgpt_token', models.CharField(max_length=255)),
            ],
        ),
    ]
