# Generated by Django 5.0 on 2023-12-15 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chatgpt_token',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client_id_token',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client_secret_token',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
