# Generated by Django 5.0 on 2023-12-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_chatgpt_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chatgpt_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client_id_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client_secret_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
