# Generated by Django 5.0 on 2023-12-19 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_alter_chatgptdocument_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptdocument',
            name='document',
            field=models.FileField(upload_to='documents/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='chatgptdocument',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
